# Generated by Django 4.0.3 on 2022-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='qoyilgan_kuni',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
