# Generated by Django 4.0.3 on 2022-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('rasm', models.URLField(blank=True)),
                ('obunachilari', models.ManyToManyField(blank=True, related_name='acc_obunachilari', to='userapp.account')),
                ('obunalar', models.ManyToManyField(blank=True, related_name='acc_obunalar', to='userapp.account')),
            ],
        ),
    ]
